vacancy_cashier_text = ("<b>Lavozimi vazifalari:</b>\n"
                      "• Kassada to'lovlarni qabul qilish va mijozlar bilan hisob-kitoblarni amalga oshirish;\n"
                      "• Har bir kassadan o'tayotgan tovarlarni skanerlash.\n"
                      "• Kassani toza saqlash.\n"
                      "<b>Talablar:</b>\n"
                      "• Yoshi: 18 yoshdan;\n"
                      "• Diqqat, xushmuomalalik, stressga qarshilik;\n"
                      "• Hisoblash qobiliyatlari.\n"
                      "<b>Ish sharoitlari:</b>\n"
                      "• Bonuslar;\n"
                      "• Mehnat kodeksiga muvofiq ishga olamiz;\n"
                      "• Oylik ish haqini o‘z vaqtida to‘laymiz;\n"
                      "• Agar tajribangiz bo'lmasa ham, biz sizni ishga olamiz va o'qitamiz;\n"
                      "• Issiq ovqat\n"
                      "• Trening va darslar.\n")
